### ISSUE TITLE
Index row size exceeds maximum

### ISSUE THREAD

**Issue by GlennRicaud** [vito/git-branch-heads-resource#4]
When using 'git-branch-heads-resource' with a repo having more than 50 branches, we get the following error:

pq: index row size 3880 exceeds maximum 2712 for index "resource_caches_resource_config_id_version_params_hash_key"

A workaround for now is to filter the branches using the source property 'branch'. But it would be easier to be able to listen to changes on any branch and remove the possibility of failure if the number of branches suddenly increases.

**Comment by vito** [comment]
Closing all these issues and deprecating the repo; concourse/concourse#1707 should remove the need for this resource type entirely.

(I also think we may have fixed this in Concourse already?)
